# Generated by Django 3.1.4 on 2020-12-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201216_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_update_delete_author', "Create, update or delete an author's detail"),)},
        ),
    ]
